### ISSUE TITLE
conda-forge setuptools has files in conflict with conda-forge python

### ISSUE THREAD

**Issue by kalefranz** [conda-forge/setuptools-feedstock#43] opened 2016-11-29 07:47 UTC
Just stumbled onto this in conda's master-branch integration testing

```
conda.exceptions.ClobberError: Conda no longer clobbers existing files without the use of the --force option.
  source path:      /usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/pkgs/setuptools-29.0.1-py35_0/lib/python3.5/__pycache__/__future__.cpython-35.pyc
  destination path: /var/folders/cp/7r2s_s593j7_cpdtxxsmct880000gp/T/21388fe5/lib/python3.5/__pycache__/__future__.cpython-35.pyc
```

Happens from an empty env when installing conda-forge python then conda-forge setuptools.

I've looked at the actual contents of both

* https://conda.anaconda.org/conda-forge/osx-64/python-3.5.2-2.tar.bz2
* https://conda.anaconda.org/conda-forge/osx-64/setuptools-29.0.1-py35_0.tar.bz2

As the exception indicates, the first clobbered file is `lib/python3.5/__pycache__/__future__.cpython-35.pyc`.

Conda 4.3 will have a pre-check phase before it starts mutating environments on disk--so that we don't fail half-way through an operation that should otherwise be transactional.  However, as is, 4.3 will not be able to install conda-forge python with conda-forge setuptools.

**Comment by kalefranz** [comment] 2016-11-29 08:05
I've confirmed the test is currently failing in the master branch, although the last CI run on Travis showed all tests passing.

https://travis-ci.org/conda/conda/builds/178719158

That test run was four days ago.  So, assuming the setuptools package is the source of the error (the files in conflict should rightfully belong to python and not setuptools), I guess the next step would be to figure out what changed between setuptools-29.0.1-py35_0 and whatever existed four days ago.

**Comment by kalefranz** [comment] 2016-11-29 08:10
I should say, I don't know the setuptools recipe history enough to assert that's actually where the problem is.  The problem could be more general, and if so, setuptools would be a natural place for it to first be triggered since conda sorts its operations in dependency order.

I think we've had a conda-build release in the last four days.  Could be a bug there.

**Comment by jakirkham** [comment] 2016-11-29 17:03
Not sure I'm totally following, sorry. May need more coffee. ☕️

It sounds sort of like issue ( https://github.com/conda-forge/conda-forge.github.io/issues/264 ). In which case, the problem would be resolved by upgrading to `conda-build` version `2.0.x` (we are still on `1.21.14` at present). Though we are working on upgrading ATM. ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/issues/40 ) So maybe we table this until we have rebuilt (at least some of) the long prefix list. ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/issues/40#issuecomment-263604581 ) We will at least need a new Python interpreter package.

If I'm misunderstanding the problem, please let me know.

**Comment by jjhelmus** [comment] 2016-11-29 17:20
The setuptools-29.0.1-py35_0 package [was built](https://travis-ci.org/conda-forge/setuptools-feedstock/jobs/179310218#L677) with a version of python 3.5 (3.5.2-3) from the `conda-forge` which is missing the `__pycache__` directory, see conda-forge/python-feedstock#70.  This package should never be installed in a conda environment for this reason and has been removed from the `main` channel.  Unfortunately, yesterday the channel labels of the python files on Anaconda.org got messed up and for a few hours this package was in the `main` channel and seems to have been used to build a few packages.  

Rebuilding the setuptools-29.0.1 package with the python 3.5.2-2 package should fix this issue.

Additionally, I would be fine deleting the broken 3.5.2-3 python package from the `conda-forge` channel on Anaconda.org.  They have been causing numerous issues which I think outweigh any benefit of having these available but disabled.

**Comment by nicoddemus** [comment] 2016-11-29 17:22
> Additionally, I would be fine deleting the broken 3.5.2-3 python package from the conda-forge channel on Anaconda.org. They have been causing numerous issues which I think outweigh any benefit of having these available but disabled.

Would generating new packages with a new build number have the same effect?

**Comment by jjhelmus** [comment] 2016-11-29 17:25
> Would generating new packages with a new build number have the same effect?

As discussed in conda-forge/python-feedstock#70, rebuilding the packages with `conda-build` `1.x` will results in packages with the same error.  Rebuilding with `conda-build` `2.x` will fix the issue but is going to take some time, conda-forge/conda-forge-build-setup#40.

**Comment by nicoddemus** [comment] 2016-11-29 17:55
Understood, just making sure I'm not missing anything and increasing the build number would be enough given we also update `conda-build` to `2.x`. 👍

**Comment by jakirkham** [comment] 2016-11-29 18:04
> The setuptools-29.0.1-py35_0 package [was built](https://travis-ci.org/conda-forge/setuptools-feedstock/jobs/179310218#L677) with a version of python 3.5 (3.5.2-3) from the `conda-forge` which is missing the `__pycache__` directory, see conda-forge/python-feedstock#70.

Good point! Have pulled Python 3.5 builds of 29.0.1 and 29.0.0, which both have this issue. Note these end up being ~1MB in size.

> Rebuilding the setuptools-29.0.1 package with the python 3.5.2-2 package should fix this issue.

Agreed. We did not have this issue with past `setuptools` packages FWICT. I think a build number bump for `master` is in order and should fix the issue.

**Comment by jakirkham** [comment] 2016-11-29 18:06
Build number bump PR ( https://github.com/conda-forge/setuptools-feedstock/pull/44 ).

**Comment by jjhelmus** [comment] 2016-11-29 18:06
> I think a build number bump for master is in order and should fix the issue.

Yes, that should take care of the issue. :+1:

**Comment by jakirkham** [comment] 2016-11-29 18:08
Ok good. Thanks for confirming and for the detailed explanation (needed my memory jogged 😄).

**Comment by jakirkham** [comment] 2016-11-29 18:27
> Additionally, I would be fine deleting the broken 3.5.2-3 python package from the conda-forge channel on Anaconda.org. They have been causing numerous issues which I think outweigh any benefit of having these available but disabled.

Would be ok with this. However, merging re-rendering PRs will likely recreate them. Would be great if we could narrow down the cause of the relabeling by the upload script. ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/issues/41 )

TBH I think your plan of getting on to `conda-build` version `2.0.x` quickly is a sound one. It should get us past many of these solved problems that are plaguing us on `1.x`. Am happy to table all other complex issues until we get there.

**Closed** 2016-12-01 15:41 UTC

**Comment by jakirkham** [comment] 2016-12-01 17:01
New Python 3.5 packages for `setuptools` version `29.0.1` appear clean. Only have Linux and Windows now. Should get Mac after Travis CI backlog has cleared up a bit.

**Comment by jjhelmus** [comment] 2016-12-02 03:13
Thanks for this @jakirkham
